name: CI alert service
on:
  push:
    branches:
      - docker-api
  workflow_dispatch:

permissions: write-all
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ENVIRONMENT_STAGE: PROD

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 18
        - name: ci
          working-directory: services/alert  
          run: npm ci
        - name: test
          working-directory: services/alert
          run: npm test