name: CI serverless app
on:
#   push:
    # ignore path
    # paths-ignore:
    #   - 'kinesis-producer/**/*'
    # branches:
    #   - main
    #   - dev
  workflow_dispatch:

permissions: write-all

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ENVIRONMENT_STAGE: PROD

jobs:
  infra:
    runs-on: ubuntu-latest
    steps:
      - name: install sls
        run: npm i -g serverless
      - uses: actions/checkout@v3
      - name: deploy to AWS
        working-directory: resources
        run: |
          echo "Deployment started on $(date)"
          echo Deploying with the serverless framework to stage $ENVIRONMENT_STAGE
          sls deploy
      - name: Post build step
        run: echo "Deployment completed on $(date)"

  ci:
    needs: 
      - infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: install serverless framework and plugins
        run: |
          echo installing serverless
          npm i -g serverless

      - uses: actions/checkout@v3
      
      - name: install sls plugins
        working-directory: stocks-alert-lambda 
        run: |
          serverless plugin install -n serverless-python-requirements
          npm ci

      - name: deploy to AWS
        working-directory: stocks-alert-lambda
        run: |
          echo "Deployment started on $(date)"
          echo Deploying with the serverless framework to stage $ENVIRONMENT_STAGE
          sls deploy
      - name: Post build step
        run: echo "Deployment completed on $(date)"