name: CI serverless app
on:
#   push:
    # ignore path
    # paths-ignore:
    #   - 'kinesis-producer/**/*'
    # branches:
    #   - main
    #   - dev
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ENVIRONMENT_STAGE: PROD

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: install serverless framework and plugins
        run: |
          echo installing serverless
          npm i -g serverless
          serverless plugin install -n serverless-python-requirements

      - uses: actions/checkout@v3
      - name: npm install
        run: |
          echo installing dependencies
          npm ci

      - name: deploy to AWS
        run: |
          echo "Deployment started on $(date)"
          echo Deploying with the serverless framework to stage $ENVIRONMENT_STAGE
          sls deploy
      - name: Post build step
        run: echo "Deployment completed on $(date)"