name: CI compare service
on:
  push:
    branches:
      - docker-api
  workflow_dispatch:

permissions: write-all
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ENVIRONMENT_STAGE: PROD

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: '3.10' 
        - name: install dependencies
          working-directory: services/compare
          run: |
             pip install -r requirements.txt
        - name: run script
          working-directory: services/compare
          run: python main.py